### ISSUE TITLE
Changes not detected in watch mode

### ISSUE THREAD

**Issue by davegomez** [koluch/esbuild-plugin-sass#6] opened 2021-03-02 23:16 UTC
Using the example configuration in my project the watch mode for the SCSS files doesn't work, but if I change the extension to CSS the build runs again every time there is a change.

Am I missing something?

**Comment by koluch** [comment] 2021-03-20 21:14
Hi @davegomez! Watch mode seems to be working fine for me, at least with the latest esbuild version (0.9.5), could you provide me with an example of code?

**Comment by koluch** [comment] 2021-04-24 22:51
Hi @davegomez! I mananed to reproduce this issue, it was fixed in v0.5.0, see #14

**Closed by koluch** 2021-04-24 22:51 UTC
