### ISSUE TITLE
SCSS modules

### ISSUE THREAD

**Issue by tskj** [koluch/esbuild-plugin-sass#16] opened 2021-04-20 09:31 UTC
What is the status on css modules with this plugin? `module.css` works fine with the regular css modules plugin, is there a way to incorporate these two plugins to work together? Or do you support modules directly?

**Comment by koluch** [comment] 2021-04-24 22:07
Hi @tskj,

No, unfortunatelly this plugin doesn't work with existed css-modules plugin, because of the way it's written (it handle modules on 'resolve' phase, so SASS-plugin will never handle it). I don't want to embed css-modules feature in this plugin, because I want it to be small and single-purpose. I actually have my own css-modules plugin, written with another approach, which works with this plugin well, I just haven't got time to publish it.

**Comment by tskj** [comment] 2021-04-26 12:36
Thanks for the reply @koluch !

I would absolutely love it if you published your other plugin as well! Without it I see no way of using "scss modules" with esbuild, which is a dealbreaker for our existing projects sadly.

**Comment by koluch** [comment] 2021-05-01 19:39
Hi @tskj,

I have published my plugin for css-modules, you can find it here: https://github.com/koluch/esbuild-plugin-css-modules. It should work fine with this plugin, you can call you sass files like `file_name.module.scss` and it will be handled properly

**Comment by tskj** [comment] 2021-05-04 11:36
Hi @koluch ,

We've been trying to integrate these two plugins, but can't seem to get it working. Do you have an example available of the configuration needed? I've attached a screenshot of our attempt.
![image](https://user-images.githubusercontent.com/25415972/116997531-34e36600-acdd-11eb-8592-ac9153e4af1c.png)

The CSS that is generated by esbuild does not seem to have hashed classnames, like you would expect with css-modules, and all classnames when imported to React are undefined. Here is a screenshot of how we do the import
![image](https://user-images.githubusercontent.com/25415972/116997706-707e3000-acdd-11eb-8f5e-3f518adbb960.png)

and here is a screenshot of the corresponding DOM.
![image](https://user-images.githubusercontent.com/25415972/116997791-8a1f7780-acdd-11eb-9ad9-95b8483d7ce0.png)

We would really appreciate your help in figuring out where we are going wrong!

**Comment by atomicpages** [comment] 2021-05-23 02:48
👋  same issue here. I found a little work around for this @tskj. It can be broken into three steps:

1. Transpile `.scss` to `.css` using `sass` and emit results in the same directory as the imported scss module
2. Using a little esbuild plugin we can transform the paths to point to the transpiled css module
3. Load the css modules plugin

The redirect plugin:

```ts
import path from 'path';
import type { Plugin } from 'esbuild';

export const redirect: Plugin = {
  name: 'redirect-to-css',
  setup(build) {
    build.onResolve({ filter: /\.scss$/ }, async args => {
      const name = path.basename(args.path, '.scss');

      return {
        path: path.resolve(args.resolveDir, `${name}.css`),
      };
    });
  },
};
```

```ts
import { redirect } from './plugins/redirect-to-css';
import css from 'esbuild-plugin-css-modules';

build({
  entryPoints: ['path/to/file'],
  bundle: true,
  plugins: [
    redirect,
    css({ localIdentName: '[local]--[hash:8:md5:hex]' })
  ]
});
```

Not a complete solution, but a step in the right direction.

**Comment by koluch** [comment] 2021-05-23 23:56
Hi @tskj,

Sorry, I missed you comments :( For some reason I haven't received notifications by github.

Two things about your code:
- you need to put SASS plugin before CSS-modules module, order matters
- you need to use `.module.css` extenstion (used by default) in CSS-modules plugin; this is because css-modules plugin works only with css files, and when you use SASS, it build temporary CSS file, with css extenstion, so css-modules plugin can handle it, knowing nothing about SASS

I am attaching working example, hope it will help
[test-with-css-modules.zip](https://github.com/koluch/esbuild-plugin-sass/files/6529127/test-with-css-modules.zip)

**Comment by tskj** [comment] 2021-05-31 12:18
Thank you so much for your working example! That's very helpful. Although, it doesn't run on my machine, but it does on my colleague's. Seems to be an issue with esbuild for me.

I don't get notifications either, so sorry for the late response as well. I have done your suggestions in our project, but still am unable to get it to work, with the following errors:
![image](https://user-images.githubusercontent.com/25415972/120188749-c67bc000-c216-11eb-8f56-2f267a0d259f.png)
The files it is referring to do exist at that path, my guess is it doesn't have permission (for some reason) to read from `/var/folders/...`?

**Comment by tskj** [comment] 2021-05-31 12:20
Curiously those files exist both with a `.module` and without. 
![image](https://user-images.githubusercontent.com/25415972/120192228-32f8be00-c21b-11eb-98f9-cdc2e334f466.png)

But that might be expected behaviour.

**Comment by koluch** [comment] 2021-06-03 16:11
No, I have no idea why it doesn't work :( Can you try to import this css file directly? Like, add `import "/var/folders/....../Tag.css"` to your TS source?

**Comment by koluch** [comment] 2021-09-05 22:45
@tskj If you still have this issue, please reopen it, I am closing it since I can't reproduce it

**Closed by koluch** 2021-09-05 22:45 UTC

**Comment by nertzy** [comment] 2021-12-22 22:17
I am running into the same issue.

When I look afterwards, the file is there. It seems to be some sort of race condition.

```
❯ ./build.js
✘ [ERROR] Could not resolve "/var/folders/tg/vwvky4sd66vgvjkl0njrkl000000gn/T/tmp-87375-BNfLN4lwtij1/scrapbook-browser/lib/style/login.css"

    ../../../../../../var/folders/tg/vwvky4sd66vgvjkl0njrkl000000gn/T/tmp-87375-BNfLN4lwtij1/scrapbook-browser/lib/style/login.module.css:2:15:
      2 │         import "/var/folders/tg/vwvky4sd66vgvjkl0njrkl000000gn/T/tmp-87375-BNfLN4lwtij1/scrapbook-browser/lib/style/login.css";
        ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "/var/folders/tg/vwvky4sd66vgvjkl0njrkl000000gn/T/tmp-87375-bqafdvagfR2x/scrapbook-browser/lib/style/login.css"

    ../../../../../../var/folders/tg/vwvky4sd66vgvjkl0njrkl000000gn/T/tmp-87375-bqafdvagfR2x/scrapbook-browser/lib/style/login.module.css:2:15:
      2 │         import "/var/folders/tg/vwvky4sd66vgvjkl0njrkl000000gn/T/tmp-87375-bqafdvagfR2x/scrapbook-browser/lib/style/login.css";
        ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tskj** [comment] 2021-12-22 22:28
I too was having the issue last time I worked on this, but I couldn't afford to dig into it anymore - and ended up giving up using esbuild all together for that project, which is quite unfortunate. I hope to try again if this is ever fixed.

**Comment by ghiculescu** [comment] 2021-12-23 17:24
> I am running into the same issue.
> 
> When I look afterwards, the file is there. It seems to be some sort of race condition.

I'm getting similar issues. Running as `sudo` resolves them but that doesn't feel like a good idea.

Running as sudo also occassionally results in other race conditions. Will try and get more details to share.

**Comment by nertzy** [comment] 2021-12-23 18:12
I opened this as an issue for esbuild-plugin-css-modules

https://github.com/koluch/esbuild-plugin-css-modules/issues/6

**Comment by ghiculescu** [comment] 2021-12-24 18:24
In the meantime I've had better luck using https://github.com/indooorsman/esbuild-css-modules-plugin

I think the main difference is that it creates a temp dir in the current working directory, rather than in `/tmp`: https://github.com/indooorsman/esbuild-css-modules-plugin/blob/main/index.js#L122
